// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v5.27.0
// source: startService.proto

package liveProto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StartService struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Platform string `protobuf:"bytes,1,opt,name=platform,proto3" json:"platform,omitempty"`
	RoomId   string `protobuf:"bytes,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	LiveUrl  string `protobuf:"bytes,3,opt,name=live_url,json=liveUrl,proto3" json:"live_url,omitempty"`
	GameId   string `protobuf:"bytes,4,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	IsTest   string `protobuf:"bytes,5,opt,name=is_test,json=isTest,proto3" json:"is_test,omitempty"`
	Nonce    string `protobuf:"bytes,6,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Sign     string `protobuf:"bytes,7,opt,name=sign,proto3" json:"sign,omitempty"`
}

func (x *StartService) Reset() {
	*x = StartService{}
	if protoimpl.UnsafeEnabled {
		mi := &file_startService_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartService) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartService) ProtoMessage() {}

func (x *StartService) ProtoReflect() protoreflect.Message {
	mi := &file_startService_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartService.ProtoReflect.Descriptor instead.
func (*StartService) Descriptor() ([]byte, []int) {
	return file_startService_proto_rawDescGZIP(), []int{0}
}

func (x *StartService) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *StartService) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *StartService) GetLiveUrl() string {
	if x != nil {
		return x.LiveUrl
	}
	return ""
}

func (x *StartService) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *StartService) GetIsTest() string {
	if x != nil {
		return x.IsTest
	}
	return ""
}

func (x *StartService) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

func (x *StartService) GetSign() string {
	if x != nil {
		return x.Sign
	}
	return ""
}

var File_startService_proto protoreflect.FileDescriptor

var file_startService_proto_rawDesc = []byte{
	0x0a, 0x12, 0x73, 0x74, 0x61, 0x72, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0xba, 0x01, 0x0a, 0x0c, 0x73, 0x74, 0x61, 0x72, 0x74, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72,
	0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72,
	0x6d, 0x12, 0x17, 0x0a, 0x07, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x6c, 0x69,
	0x76, 0x65, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6c, 0x69,
	0x76, 0x65, 0x55, 0x72, 0x6c, 0x12, 0x17, 0x0a, 0x07, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x69, 0x64,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x67, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x12, 0x17,
	0x0a, 0x07, 0x69, 0x73, 0x5f, 0x74, 0x65, 0x73, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x69, 0x73, 0x54, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6e, 0x6f, 0x6e, 0x63, 0x65,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x73, 0x69, 0x67, 0x6e, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x69, 0x67,
	0x6e, 0x42, 0x0d, 0x5a, 0x0b, 0x2f, 0x3b, 0x6c, 0x69, 0x76, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_startService_proto_rawDescOnce sync.Once
	file_startService_proto_rawDescData = file_startService_proto_rawDesc
)

func file_startService_proto_rawDescGZIP() []byte {
	file_startService_proto_rawDescOnce.Do(func() {
		file_startService_proto_rawDescData = protoimpl.X.CompressGZIP(file_startService_proto_rawDescData)
	})
	return file_startService_proto_rawDescData
}

var file_startService_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_startService_proto_goTypes = []interface{}{
	(*StartService)(nil), // 0: startService
}
var file_startService_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_startService_proto_init() }
func file_startService_proto_init() {
	if File_startService_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_startService_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartService); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_startService_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_startService_proto_goTypes,
		DependencyIndexes: file_startService_proto_depIdxs,
		MessageInfos:      file_startService_proto_msgTypes,
	}.Build()
	File_startService_proto = out.File
	file_startService_proto_rawDesc = nil
	file_startService_proto_goTypes = nil
	file_startService_proto_depIdxs = nil
}
